apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-db
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "myapp.name" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "myapp.name" . }}-db
    spec:
      containers:
        - name: postgres
          image: "postgres:13-alpine"
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.db }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-storage
          persistentVolumeClaim:
            claimName: {{ include "myapp.fullname" . }}-pvc

