apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-release-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/ansible/1

